#!/bin/sh
echo 3
sleep 1
echo 2
sleep 1
echo 1
sleep 1

cd .config

if [ -e "$HOME/.config/zsh" ]; then
    cp -r $HOME/.config/zsh /tmp/zsh-backup
    rm -rf $HOME/.config/zsh
fi

cp -r .config/zsh $HOME/.config/
